language: java

sudo: false

jdk:
- openjdk8

install:
- mvn clean install -DskipTests -B -U

script:
- sh ./check_format.sh
- cd sofa-ark-samples && mvn clean install -q
- cd sample-ark-plugin && mvn clean install -q
- cd ../sample-springboot-ark && mvn test -q
- cd ../..

after_success:
- mvn clean test
- bash <(curl -s https://codecov.io/bash)
